name: ing_soft_examen1

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test:ci

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hola! este workflow se ejecuta al realizar un commit-push a la branch ${{ github.ref }}"
    - run: echo "Origen del evento ${{ github.actor }}."
    - run: echo "La indicación en el portal decia que se ejecutara al realizar un commit pero asumo a que se refiere a un commit->push"
      
    - run: echo "Estado ${{ job.status }}."  
